name: Deploy using Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Run Ansible Playbook
      run: |
        ssh -o StrictHostKeyChecking=no root@38.75.137.11 << 'EOF'
          ansible-playbook /etc/ansible/playbooks/theincorp_deploy.yml
        EOF

    - name: Send email notification on success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yandex.com
        server_port: 465
        username: deployment-alerts@voxtrongroup.com
        password: DevOps123$%67
        subject: "Deployment Successful"
        body: |
          The deployment to the server has been successfully completed.
          Site URL: "theincorpsolutions.com"
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
        to: "devops@voxtrongroup.com"
        from: "deployment-alerts@voxtrongroup.com"

    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.yandex.com
        server_port: 465
        username: deployment-alerts@voxtrongroup.com
        password: DevOps123$%67
        subject: "Deployment Failed - Rollback Executed"
        body: |
          The deployment to the server has failed and a rollback has been executed.
          Please check the logs for more details.
          Site URL: "theincorpsolutions.com"
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
        to: "devops@voxtrongroup.com"
        from: "deployment-alerts@voxtrongroup.com"
